//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//#import "NSObject.h"

#import <CoreBluetooth/CoreBluetooth.h>


/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Sharing.framework/Versions/A/Sharing
 */

@interface SFBLEScanner : NSObject <CBCentralManagerDelegate> {
    BOOL  _activateCalled;
    BOOL  _activated;
    BOOL  _activeScan;
    id  _bluetoothStateChangedHandler;
    CBCentralManager * _centralManager;
    unsigned int  _changeFlags;
    id  _deviceChangedHandler;
    NSArray * _deviceFilter;
    id  _deviceFoundHandler;
    id  _deviceLostHandler;
    struct NSMutableDictionary { Class x1; } * _devices;
    NSObject<OS_dispatch_queue> * _dispatchQueue;
    BOOL  _invalidateCalled;
    id  _invalidationHandler;
    NSObject<OS_dispatch_source> * _lostTimer;
    BOOL  _needDups;
    NSData * _payloadFilterData;
    NSData * _payloadFilterMask;
    long long  _payloadType;
    bool  _poweredOffSleep;
    double  _rescanInterval;
    int  _rescanSecondsActual;
    NSObject<OS_dispatch_source> * _rescanTimer;
    struct __sFILE * _rssiEventLogFile;
    BOOL  _rssiLog;
    BOOL  _rssiLogStdOut;
    long long  _rssiThreshold;
    BOOL  _scanCache;
    long long  _scanInterval;
    BOOL  _scanParamActive;
    BOOL  _scanParamCache;
    BOOL  _scanParamDups;
    NSData * _scanParamFilterData;
    NSData * _scanParamFilterMask;
    long long  _scanParamInterval;
    long long  _scanParamMode;
    NSArray * _scanParamPeers;
    long long  _scanParamRSSI;
    long long  _scanParamWindow;
    long long  _scanRate;
    BOOL  _scanStarted;
    long long  _scanState;
    id  _scanStateChangedHandler;
    long long  _scanWindow;
//    CURetrier * _startRetrier;
    double  _timeout;
    BOOL  _timeoutFired;
    id  _timeoutHandler;
    NSObject<OS_dispatch_source> * _timeoutTimer;
    NSSet * _trackedPeers;
    NSSet * _trackedPeersApplied;
    struct LogCategory { int x1; int x2; char *x3; unsigned int x4; char *x5; char *x6; int x7; struct LogCategory *x8; struct LogOutput *x9;  struct LogOutput *x10; unsigned long long x11; unsigned long long x12; unsigned int x13; unsigned int x14; char *x15; struct LogCategoryPrivate {} *x16; } * _ucat;
    BOOL  _updating;
    id  _wpAirDrop;
    id _wpNearby;
    long long  _wpNearbyType;
    id _wpPairing;
}

@property (nonatomic, copy) id bluetoothStateChangedHandler;
@property (nonatomic) unsigned int changeFlags;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, copy) id deviceChangedHandler;
@property (nonatomic, copy) NSArray *deviceFilter;
@property (nonatomic, copy) id deviceFoundHandler;
@property (nonatomic, copy) id deviceLostHandler;
@property (nonatomic, retain) NSObject<OS_dispatch_queue> *dispatchQueue;
@property (readonly) unsigned long long hash;
@property (nonatomic, copy) id invalidationHandler;
@property (nonatomic, readonly, copy) NSData *payloadFilterData;
@property (nonatomic, readonly, copy) NSData *payloadFilterMask;
@property (nonatomic) double rescanInterval;
@property (nonatomic) BOOL rssiLog;
@property (nonatomic) BOOL rssiLogStdOut;
@property (nonatomic) long long rssiThreshold;
@property (nonatomic) BOOL scanCache;
@property (nonatomic) long long scanInterval;
@property (nonatomic) long long scanRate;
@property (nonatomic, readonly) long long scanState;
@property (nonatomic, copy) id scanStateChangedHandler;
@property (nonatomic) long long scanWindow;
@property (readonly) Class superclass;
@property (nonatomic) double timeout;
@property (nonatomic, copy) id timeoutHandler;
@property (nonatomic, copy) NSSet *trackedPeers;

//- (void).cxx_destruct;
- (void)_activateWithCompletion:(id)arg1;
- (void)_foundDevice:(id)arg1 advertisementData:(id)arg2 rssi:(long long)arg3 fields:(id)arg4;
- (void)_invalidate;
- (void)_invokeBlockActivateSafe:(id)arg1;
- (void)_nearbyParseManufacturerData:(id)arg1 fields:(id)arg2;
- (void)_nearbyParseNearbyActionPtr:(const char *)arg1 end:(const char *)arg2 fields:(id)arg3;
- (void)_nearbyParseNearbyInfoPtr:(const char *)arg1 end:(const char *)arg2 fields:(id)arg3;
- (BOOL)_needActiveScan;
- (BOOL)_needDups;
- (void)_poweredOff;
- (void)_poweredOn;
- (void)_removeAllDevicesWithReason:(id)arg1;
- (void)_rescanLostFired;
- (void)_rescanTimerFired;
- (void)_restartIfNeeded;
- (void)_restartIfNeeded:(BOOL)arg1;
- (void)_rssiLogClose;
- (void)_rssiLogOpen;
- (void)_startTimeoutIfNeeded;
- (void)_timeoutTimerFired;
- (BOOL)_updateCounterpart:(id)arg1;
- (void)_updateRescanTimer;
- (void)_updateTrackedPeers;
- (void)_watchSetupParseName:(id)arg1 fields:(id)arg2;
- (void)activateWithCompletion:(id)arg1;
- (void)awdl:(id)arg1 failedToStartScanningWithError:(id)arg2;
- (void)awdl:(id)arg1 foundDevice:(id)arg2 rssi:(id)arg3;
- (void)awdlDidUpdateState:(id)arg1;
- (void)awdlStartedScanning:(id)arg1;
- (id)bluetoothStateChangedHandler;
- (void)centralManager:(id)arg1 didDiscoverPeripheral:(id)arg2 advertisementData:(id)arg3 RSSI:(id)arg4;
- (void)centralManagerDidUpdateState:(id)arg1;
- (unsigned int)changeFlags;
- (void)dealloc;
- (id)description;
- (id)deviceChangedHandler;
- (id)deviceFilter;
- (id)deviceFoundHandler;
- (id)deviceLostHandler;
- (id)dispatchQueue;
- (id)initWithType:(long long)arg1;
- (void)invalidate;
- (id)invalidationHandler;
- (id)modelWithProductID:(unsigned short)arg1;
- (void)nearby:(id)arg1 didDiscoverType:(long long)arg2 withData:(id)arg3 fromPeer:(id)arg4 peerInfo:(id)arg5;
- (void)nearby:(id)arg1 didFailToStartScanningForType:(long long)arg2 WithError:(id)arg3;
- (void)nearby:(id)arg1 didLosePeer:(id)arg2 type:(long long)arg3;
- (void)nearby:(id)arg1 didStartScanningForType:(long long)arg2;
- (void)nearbyDidUpdateState:(id)arg1;
- (void)pairing:(id)arg1 failedToStartScanningWithError:(id)arg2;
- (void)pairing:(id)arg1 foundDevice:(id)arg2 payload:(id)arg3 rssi:(id)arg4 peerInfo:(id)arg5;
- (void)pairingDidUpdateState:(id)arg1;
- (id)pairingParsePayload:(id)arg1 identifier:(id)arg2 bleDevice:(id)arg3;
- (void)pairingStartedScanning:(id)arg1;
- (BOOL)pairingUpdatePairedInfo:(id)arg1 fields:(id)arg2 bleDevice:(id)arg3;
- (void)parseStatus3:(unsigned char)arg1 productID:(unsigned int)arg2 caseLEDColor:(char *)arg3 caseLEDStatus:(char *)arg4;
- (id)payloadFilterData;
- (id)payloadFilterMask;
- (void)performUpdate:(id)arg1;
- (double)rescanInterval;
- (BOOL)rssiLog;
- (BOOL)rssiLogStdOut;
- (long long)rssiThreshold;
- (BOOL)scanCache;
- (long long)scanInterval;
- (long long)scanRate;
- (long long)scanState;
- (id)scanStateChangedHandler;
- (long long)scanWindow;
- (void)setBluetoothStateChangedHandler:(id)arg1;
- (void)setChangeFlags:(unsigned int)arg1;
- (void)setDeviceChangedHandler:(id)arg1;
- (void)setDeviceFilter:(id)arg1;
- (void)setDeviceFoundHandler:(id)arg1;
- (void)setDeviceLostHandler:(id)arg1;
- (void)setDispatchQueue:(id)arg1;
- (void)setInvalidationHandler:(id)arg1;
- (void)setPayloadFilterData:(id)arg1 mask:(id)arg2;
- (void)setRescanInterval:(double)arg1;
- (void)setRssiLog:(BOOL)arg1;
- (void)setRssiLogStdOut:(BOOL)arg1;
- (void)setRssiThreshold:(long long)arg1;
- (void)setScanCache:(BOOL)arg1;
- (void)setScanInterval:(long long)arg1;
- (void)setScanRate:(long long)arg1;
- (void)setScanStateChangedHandler:(id)arg1;
- (void)setScanWindow:(long long)arg1;
- (void)setTimeout:(double)arg1;
- (void)setTimeoutHandler:(id)arg1;
- (void)setTrackedPeers:(id)arg1;
- (unsigned int)statusToHeadsetStatus:(unsigned char)arg1;
- (double)timeout;
- (id)timeoutHandler;
- (id)trackedPeers;

@end
